package main

/*
 * Even Fibonacci numbers
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms
 * will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 * By considering the terms in the Fibonacci sequence whose values do
 * not exceed four million, find the sum of the even-valued terms.
 */

import "fmt"

func main() {
	sum := 0
	j,k := 0,0
	for i := 1; sum < 4000000; i = j + k {
		fmt.Printf("i: %d\n", i)
		if i % 2 == 0 {
			sum += i
		}
		k = j
		j = i
	}
	fmt.Printf("Sum: %d\n", sum)
}
